/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_recompile_mobile_Audio */

#ifndef _Included_org_recompile_mobile_Audio
#define _Included_org_recompile_mobile_Audio
#ifdef __cplusplus
extern "C" {
#endif
int getVolumeLevel();

/*
 * Class:     org_recompile_mobile_Audio
 * Method:    _setVol
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_recompile_mobile_Audio__1setVol
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_recompile_mobile_Audio
 * Method:    _destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_recompile_mobile_Audio__1destroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
